on:
  push:
    tags:
      - v*.*.*

name: Release

jobs:
  build:
    strategy:
      matrix:
        name:
          # - advertise-linux-amd64-gnu
          - ipam-da-consul-linux-amd64-gnu
          - ipam-ds-nomad-linux-amd64-gnu
          - ipam-delegated-linux-amd64-gnu

        include:
          # - name: advertise-linux-amd64-gnu
          #   plugin: advertise
          #   os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   cross: false

          - name: ipam-delegated-linux-amd64-gnu
            plugin: ipam-delegated
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

          - name: ipam-da-consul-linux-amd64-gnu
            plugin: ipam-da-consul
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

          - name: ipam-ds-nomad-linux-amd64-gnu
            plugin: ipam-ds-nomad
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

    name: Release ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build (standard)
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target ${{ matrix.target }} --bin ${{ matrix.plugin }}
      - name: Package (standard)
        run: bash .github/workflows/package.sh "${{ matrix.plugin }}" "${{ matrix.target }}" "${{ github.ref }}"

      - uses: actions-rs/cargo@v1
        name: Build (verbose)
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target ${{ matrix.target }} --bin ${{ matrix.plugin }} --features release-logs
      - name: Package (verbose)
        run: bash .github/workflows/package.sh "${{ matrix.plugin }}" "${{ matrix.target }}" "${{ github.ref }}" verbose

      - uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.zst"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
